apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-3fxv
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/kpiwko-tenant/my-app-2/devfile-sample-3fxv@sha256:15c2365d12a1678e3333cdafae0e04e60350545bd8a245e9c65e55dbed208fbe
        name: my-nodejs
        resources: {}
status: {}
